### ISSUE TITLE
projectConfig.js wrong value for 'project'

### ISSUE THREAD

**Issue by hummelch** [biotope/biotope-boilerplate#101]
## Expected behavior
https://github.com/biotope/biotope-boilerplate/blob/6.0.0/projectConfig.js
I would expact 'Biotope 6' here.

## Actual behavior
VI Frontend Framework 5

## Steps to reproduce
https://github.com/biotope/biotope-boilerplate/blob/6.0.0/projectConfig.js

  - Biotope Version: 6.0.0

**Comment by jurekbarth** [comment]
Would you like to submit a PR? 👍
