### ISSUE TITLE
add watchScss to projectConfig

### ISSUE THREAD

**Issue by karlbaumhauer** [biotope/biotope-boilerplate#126]
## Expected behavior
Live reload

## Actual behavior
stop and start npm for effecting changes

## Steps to reproduce

  1. start npm
  2. change style
  3. reload website

## Specifications

  - Biotope Version: 6.2.0
  - Node Version: 11.13
  - Yarn Version:
  - Operating System: macOS 10.14.5
  - Browser & Version: Firefox Developer Edition 68.0b11

**Comment by SheepFromHeaven** [comment]
Resolved by #129
