### ISSUE TITLE
Adding NPX to biotope-boilerplate

### ISSUE THREAD

**Issue by karlbaumhauer** [biotope/biotope-boilerplate#127]
## Expected behavior
having NPX installed via npm install from the start on

## Actual behavior
NPX needs to be installed manually 

## Steps to reproduce

  1. clone boilerplate
  2. generate a new component 
  3. NPX is temporarily installing to generate the component each time

## Specifications

- Biotope Version: 6.2.0
- Node Version: 11.13
- Yarn Version:
- Operating System: macOS 10.14.5
- Browser & Version: Firefox Developer Edition 68.0b11

**Comment by SheepFromHeaven** [comment]
@karlbaumhauer as I get it, you want to have the biotope-cli installed, right? NPX ist just a tool, similar to NPM which helps to run uninstalled packages temporally

**Comment by karlbaumhauer** [comment]
yes... you are right...
thx for explaining it...;-)
________________________________
