### ISSUE TITLE
Implement testing possibilities to test typescript

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-boilerplate#20]
Current:
We have no default testing for ts/js unit tests.

Wish:
There is an easy method to register tests and have them run automagically.

**Comment by jurekbarth** [comment]
I would really like to close here and add that stuff to the cli. Something like `npx @biotope/cli install testsuite`

**Comment by SheepFromHeaven** [comment]
Moved to biotope/biotope-cli#28
