### ISSUE TITLE
Extract demo components to demo branch

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-boilerplate#32]
Currently there are still "Demo" components in the master branch. We should move them to the demo branch.

**Comment by luke-m** [comment]
I suppose you are referring to the `icons` component and everything inside `framework` should stay as is, right?

**Comment by timomayer** [comment]
@luke-m in my oppinion only header and footer should be inside of the boilerplate.
breadcrumb should be moved to the compnents-example branch.
grid: should be extracted to its own repo (biotope-world-domination-grid) and reintrated to biotope-boilerplate as an NPM dependency

**Comment by luke-m** [comment]
Grid extracted to [this](https://github.com/biotope/biotope-world-domination-grid) repo, which is also a NPM package. 
`demo-5.x` branch renamed to `components-example`. This branch incorporates the grid system and all the demo components.
