### ISSUE TITLE
Remove references to vi coding guidelines

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-boilerplate#35]
Current:
We reference the coding guidelines from VI as best practices

Wish:
To become it's own product, there should be no more references to the coding guidelines, as it is up to the developer.

@timomayer what do you think?

**Comment by timomayer** [comment]
i agree. coding guidlines should not be part of biotope and therefor not referenced

**Comment by luke-m** [comment]
Is this just concerning the CSS / SCSS section or what else are you referring to specifically?
