### ISSUE TITLE
Move the new biotope-core

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-boilerplate#48]
Move the new biotope-core to its own project

https://github.com/biotope/biotope/tree/beta/src/resources/ts/core
https://github.com/biotope/biotope/tree/beta/src/resources/ts/state

@timomayer @janrembold what do you think?

**Comment by timomayer** [comment]
+1

**Comment by SheepFromHeaven** [comment]
@timomayer please use the github +1 feature 😄

**Comment by timomayer** [comment]
Wenn du mir sagst wo in Outlook der Knopf dafür ist 😉

Von: Marc Wißler <notifications@github.com>
Gesendet: Mittwoch, 6. Juni 2018 11:10
An: biotope/biotope-boilerplate <biotope-boilerplate@noreply.github.com>
Cc: Timo Mayer <timo.mayer@virtual-identity.com>; Mention <mention@noreply.github.com>
Betreff: Re: [biotope/biotope-boilerplate] Move the new biotope-core (#48)


@timomayer<https://github.com/timomayer> please use the github +1 feature 😄

**Comment by jurekbarth** [comment]
It's already done:
https://github.com/biotope/biotope-core

Close for now, if needed reopen please :)
