### ISSUE TITLE
rename the repo

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-boilerplate#52]
## Expected behavior
i expect to have a rough understanding of what a repo is for by reading its repo name.

## Actual behavior
biotope/biotope confuses. i suggest to rename it to biotope/biotope-seed, biotope/biotope-boilerplate ?

**Comment by jurekbarth** [comment]
For me biotope/biotope-boilerplate makes the most sense.

**Comment by timomayer** [comment]
done
