### ISSUE TITLE
yarn start doesnt work

### ISSUE THREAD

**Issue by bennyvi** [biotope/biotope-boilerplate#53]
## Expected behavior
start the development environment run **yarn start**

## Actual behavior
error Command "start" not found.

## Steps to reproduce

  1.  Open your command line/terminal/bash
  2. Navigate to the project folder
  3. Run yarn install
  4. Run yarn start

**Comment by timomayer** [comment]
please check if the scripts part in your package.json has latest start scripts in or if not copy them over from:
https://github.com/biotope/biotope-boilerplate/blob/master/package.json

**Comment by bennyvi** [comment]
Ok worked with the latest version :) Thank you
