### ISSUE TITLE
SCSS IntelliSense throws UnhandledPromiseRejectionWarning when starting serve process

### ISSUE THREAD

**Issue by luke-m** [biotope/biotope-boilerplate#58]
## Expected behavior
No errors thrown.

## Actual behavior
The following error comes up in the VSCode SCC IntelliSense log: 
`[Error - 09:27:55] (node:13924) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: ENOENT: no such file or directory, stat 'c:\Users\lukas.mueller\Documents\dev\biotope\src\resources\scss\utilities\functions.scss'`

## Steps to reproduce

  1. Open (clean) biotope project in VSCode
  2. `yarn start`
  3. check SCSS IntelliSense output

## Specifications

  - Biotope Version: 5.4.0
  - Node Version: 8.10.0
  - Yarn Version: 1.7.0
  - Operating System: Windows 10 Pro (Version 10.0.16299 Build 16299)
  - VSCode Version: 1.25.0-insider

**Comment by SheepFromHeaven** [comment]
@luke-m is this still an issue?
