### ISSUE TITLE
Rename icon.scss to icon.tpl

### ISSUE THREAD

**Issue by koepferd** [biotope/biotope-boilerplate#63]
## Expected behavior
After cloning the project will build without warnings.

## Actual behavior
Warning in IconFont task: file does not exist, src/resources/scss/fonts/iconfont/_icons.tpl
Renaming src/resources/scss/fonts/iconfont/_icons.scss to _icons.tpl will fix this.

## Steps to reproduce

  1. clone project
  2. yarn install
  3. yarn start
  4. enjoy your warning

## Specifications

  - Biotope Version: 5.4.0
  - Node Version: >=8.9.0
  - Yarn Version: >=1.4.0
  - Operating System: Windows

@dweiger : was changed in biotope-build (https://github.com/biotope/biotope-build/pull/102) but not adjusted in biotope-boilerplate

**Comment by timomayer** [comment]
@koepferd there is already an open PR for that. version 5.4.0 of boilerplat eis not yet tagged. please use always latest released version instead of master :)

**Comment by timomayer** [comment]
i now released 5.4.0
