### ISSUE TITLE
Dependency 'vi-css-helper' not found when performing 'yarn install'

### ISSUE THREAD

**Issue by jwahler** [biotope/biotope-boilerplate#8]
https://github.com/frontend-framework/frontend-framework/blob/a383536f08d37ca2c41a298507fbf69129c3f323/package.json#L31

IMHO the path should point to: https://github.com/virtualidentityag/vi-css-helper#1.1.1

**Comment by timomayer** [comment]
@jwahler I can not reproduce this issue. Is it still relevant?

**Comment by pwltr** [comment]
Hi,
I had the same issue. @jwahler solution worked for me.

**Comment by SheepFromHeaven** [comment]
@timomayer for me this is referenced to #35 . We should not have references to vi helpers in the repo, as biotope is it's own product. right?

**Comment by timomayer** [comment]
for me thats not a must. we use third party libs like normalize so another 3rd party lib from vi is not a real issue imho and does not mean biotope is not an independent product. what do you think?

**Comment by jurekbarth** [comment]
@jwahler @pwltr any updates? Or can you please further explain whats wrong?

**Comment by smohadjer** [comment]
I ran into this problem today as well after removing node_modules from my project and running yarn install, but this is not a biotope issue.
