### ISSUE TITLE
RFC: Get rid of the resources folder

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-boilerplate#83]
I propose to get rid of the resources folder, as everything should live inside a component to guaranty reusability. This ticket is for discussion around that topic and for collection of risks.

**Comment by SheepFromHeaven** [comment]
**Q:** What about global styles?

**Comment by SheepFromHeaven** [comment]
**Q:** What about icontfonts/SVG sprites?

**Comment by jurekbarth** [comment]
I think the resources folder could be removed but still there's a need for some folder structure for helpers. Something like lodash but more customized.

SVG Sprites could be a web component rendering that icon for you. We would need a svg loader and then they would be bundled with a little bit of js. For usage in CSS we could start with including single items, so an SVG Sprite would make sense here.

Global Styles: I would like to try out what styled-component does in React. They have a *theme* component that does global styles as well as variables. --> here we could progressively enhance with css custom properties. So we could change styles at runtime.
