### ISSUE TITLE
RFC: vNext

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-boilerplate#84]
@tiagomapmarques I would propose a change in the folder structure for vNext in comparison to your v7 branch:

In my opinion, there should be only a components and a common folder (you called it services)

What do you think @biotope/core-enforcer ?

**Comment by jurekbarth** [comment]
@SheepFromHeaven i think it's legit to have a `resources` folder but i would rename it to `public` and then resolve it to `root` on build, like every framework does it. I like the change from `services` to `common`. The other folders are not necessary imho, sure a theme folder or something like this would be nice, but without a working solution for themes i would remove it.
