### ISSUE TITLE
Resource Loader not dispatching event "resourcesReady"

### ISSUE THREAD

**Issue by jurekbarth** [biotope/biotope-boilerplate#88]
## Expected behavior
If you use the resource loader in a component and every resource got loaded it should fire an event for completion, e.g. to initialize components with `data-init`

## Actual behavior
Event is not fired, the first file the resource loader picks up is stuck in the queue.

## Steps to reproduce
  1. Checkout
  2. Create a component and some js/ts file include it via the resource loader
  3. Watch `src/resources/ts/main.ts` for the event

## Specifications

  - Biotope Version: 6
  - Node Version: 11
  - Operating System: Mac OS

**Comment by timomayer** [comment]
This is a loader issue and duplicates this one https://github.com/biotope/biotope-resource-loader/issues/5

**Comment by jurekbarth** [comment]
@timomayer did that not work already? But yes it's for sure related 👍

**Comment by jurekbarth** [comment]
@SheepFromHeaven any clue?

**Comment by SheepFromHeaven** [comment]
Done in resource loader
